version: '3'

services:
  db:
    container_name: posts_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - posts_data:/var/lib/postgresql/data

#  api:
#    container_name: compose-api
#    build:
#      context: .
#      dockerfile: Dockerfile.multi
#    ports:
#      - 8080:8080
#    environment:
#      DB_USER: postgres
#      DB_PASSWORD: 1234
#      DB_NAME: postgres
#      DB_HOST: postgres_db
#      DB_PORT: 5432

volumes:
  posts_data: