server:
  error:
    include-message: always
  servlet:
    context-path: /api/post
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

AUTH_PORT: 8080
AUTH_HOST: localhost
