server:
  servlet:
    context-path: /api
spring:
  jpa:
    hibernate:
     ddl-auto: create-drop
    database: postgresql
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver